### ISSUE TITLE
Enhancement: convert to `customtkinter`

### ISSUE THREAD

**Issue by dishb** [jacobranz/student_management_system#29]
`customtkinter` is much more modern and would make the application more visually pleasing.

**Comment by jacobranz** [comment]
This is a great idea, you guys have done some nice work. I will make not of this.

**Comment by dishb** [comment]
Should be relatively simple, some things may need to be adjusted...

**Comment by jacobranz** [comment]
Will work on that, I see you have made some good contributions other places. Feel free to do the same wherever you see fit!

**Comment by dishb** [comment]
Of course, hopefully I can start Thursday 🙂

**Comment by dishb** [comment]
Since there are many Python files that use `tkinter`, I'd suggest creating a Project in this repo for the conversion. It would help keep things more organized. Furthermore, its OK to leave some files with `tkinter` and some with `customtkinter` as the two are supposed to interact with each other well.

**Comment by dishb** [comment]
PR #33 was created to convert `main.py` to `customtkinter` for this issue.

**Comment by jacobranz** [comment]
Creating new branch to handle conversion of tkinter to customtkinter.

**Comment by dishb** [comment]
I'll work on a new PR sometime this weekend (PST). Thanks!

**Comment by dishb** [comment]
@jacobranz - Maybe delete #32 and #33 ?

**Comment by jacobranz** [comment]
Codebase has been converted, cleanup still to be done. But tests with customtkinter now work. Closing.
